# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e5fce56408c06c6019967816d80e80f566fe8c84c3c03f2d7d419df31c5f239c480d0bf5c8ea15d194834df84560f90ec308ca5718e5b623bf743cab8b32b8f

test:
  secret_key_base: 47c0f719458c520171dca7d38ac9a9d6b7e06a3a553dc5580edcbec5edad9bfc1814cdba16770e4af2169b55c71be73cf6d025c6962fc661e2fbf9ec5d628426

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
